### ISSUE TITLE
Tutorial on how to run

### ISSUE THREAD

**Issue by loretoparisi** [tranhungnghiep/PaperRecommender#1]
Thank you for this work! Could you please describe how to run this recommender with NetBeans?

**Comment by tranhungnghiep** [comment]
Hello, sorry for the late response. Somehow I didn't get notification.

The main entry point of the program is at the method `recommendationFlowController` in the file `https://github.com/tranhungnghiep/PaperRecommender/blob/master/src/uit/tkorg/pr/controller/PRCentralController.java`.

You will see the main method with an example of how to pass parameters to the method. There are some explanations for parameters in the javadocs of the method. Mainly, you specify the dataset, in input directories path, the output evaluation file path, the methods to run.

Because this is research code so it is very highly customized to my past experiments, you may find it more usable to extract parts of the source code that you need.
